### ISSUE TITLE
Closing interstitial ad will call onStateChange twice

### ISSUE THREAD

**Issue by jnrepo** [mraid/webtester#14]
When closing an interstitial ad, the MRAID SDK will call onStateChange to `hidden` twice.  I've noticed that on inline ads, it'll only call `hidden` once.  I'm not too sure why this is, I think it could be a bug and it makes this state difficult and confusing to track.

**Comment by ncarver** [comment]
Hi Joon, 

Do you have some code you can contribute to address this? It might be the fastest way to improve the webtester.

Thanks,
-Nathan
