### ISSUE TITLE
MRAID ad creative working fine in webtester but not in app tester

### ISSUE THREAD

**Issue by mahendrarevx** [mraid/webtester#32]
Hi, 
I am developing an MRAID ad creative. While the creatives functions exactly as I wish it to in the webtester, it does not function properly in the MRAID Ads SDK Tester and Mopub Sample App. What can be the issue? I need this to resolved urgently.

**Comment by ncarver** [comment]
Sorry you're having troubles getting your mraid creative to work across platforms. Sometimes this an issue with the creative, but sometimes it is an issue with the hosting platform. Each platform has it's own quirks (including the webtester).

My suggestion is to create an area on top of your ad for logging. Its very hard to know what's happening in a container without it. Use a centered DIV for example where you can output logs, then simply hide the DIV element when your troubleshooting is done.

Good luck.
-Nathan
