### ISSUE TITLE
Add license text

### ISSUE THREAD

**Issue by goneall** [mraid/webtester#38]
Many of the source files refer to a LICENSE file being at the "root of the source tree".  I could not locate this file in this repository.  It would be helpful for downstream users wishing to comply with the attribution requirements of the BSD license to have easy access to the original license text.

**Comment by ncarver** [comment]
Thanks for your note. I've added the 2-clause BSD license file to the project root.

**Comment by goneall** [comment]
@ncarver Thanks for the quick response.
