### ISSUE TITLE
switching between portrait/landscape mode in the test stage does not set the ad unit dimensions correctly

### ISSUE THREAD

**Issue by jonathanong** [mraid/webtester#7]
it sets the width as height and vice versa. very annoying as it's difficult to test orientation changes. happens at 640x480 but not 320x480

**Comment by AParsonsADITION** [comment]
by setting the ad unit dimensions correctly, do you mean that the mraid.getCurrentPosition() returns the switched width and height values after rotating from portrait to landscape and then back to portrait orientation? This is the problem I am currently having and not sure if that is the same problem as yours?
